In [1]:
import requests as r
from bs4 import BeautifulSoup
import pandas as pd
import datetime as dt
from sqlalchemy import create_engine # database connection

In [2]:
res = r.get('http://www.thsrc.com.tw/tw/TimeTable/DailyTimeTable/20160606')

In [3]:
soup = BeautifulSoup(res.text, "lxml")

In [4]:
table = soup.find('table')

In [5]:
table

In [65]:
south_bound = pd.read_html(str(table), flavor="lxml")[3]
south_bound.columns = south_bound.iloc[0]
south_bound = south_bound.reindex(south_bound.index.drop(0))
stations = south_bound.columns.get_values()[2:]
for station in stations:
    south_bound[station] = '20160606 ' + south_bound[station].astype(str)
    south_bound[station] = pd.to_datetime(south_bound[station], format='%Y%m%d %H:%M', errors="coerce")
south_bound
#south_bound.ix[:,2]

,車次,南港站,台北站,板橋站,桃園站,新竹站,苗栗站,台中站,彰化站,雲林站,嘉義站,台南站,左營站
1,0581,NaN,NaT,NaT,NaT,NaT,NaT,2016-06-06 06:30:00,2016-06-06 06:44:00,2016-06-06 06:55:00,2016-06-06 07:07:00,2016-06-06 07:28:00,2016-06-06 07:42:00
2,0801,NaN,2016-06-06 06:30:00,2016-06-06 06:38:00,2016-06-06 06:51:00,2016-06-06 07:03:00,2016-06-06 07:15:00,2016-06-06 07:36:00,2016-06-06 07:49:00,2016-06-06 08:00:00,2016-06-06 08:12:00,2016-06-06 08:32:00,2016-06-06 08:48:00
3,0101,NaN,2016-06-06 06:36:00,2016-06-06 06:45:00,NaT,NaT,NaT,2016-06-06 07:26:00,NaT,NaT,NaT,NaT,2016-06-06 08:12:00
4,0807,NaN,2016-06-06 07:00:00,2016-06-06 07:08:00,2016-06-06 07:21:00,2016-06-06 07:33:00,2016-06-06 07:45:00,2016-06-06 08:06:00,2016-06-06 08:19:00,2016-06-06 08:30:00,2016-06-06 08:45:00,2016-06-06 09:04:00,2016-06-06 09:18:00
5,1107,NaN,2016-06-06 07:06:00,2016-06-06 07:15:00,NaT,NaT,NaT,2016-06-06 07:56:00,NaT,NaT,NaT,NaT,2016-06-06 08:42:00
6,1505,NaN,2016-06-06 07:18:00,2016-06-06 07:26:00,2016-06-06 07:39:00,2016-06-06 07:51:00,2016-06-06 08:03:00,2016-06-06 08:20:00,NaT,NaT,NaT,NaT,NaT
7,0109,NaN,2016-06-06 07:24:00,2016-06-06 07:33:00,NaT,NaT,NaT,2016-06-06 08:15:00,NaT,NaT,NaT,NaT,2016-06-06 09:00:00
8,0609,NaN,2016-06-06 07:36:00,2016-06-06 07:45:00,2016-06-06 08:00:00,2016-06-06 08:13:00,NaT,2016-06-06 08:39:00,NaT,NaT,2016-06-06 09:04:00,2016-06-06 09:23:00,2016-06-06 09:36:00
9,0611,NaN,2016-06-06 07:48:00,2016-06-06 07:56:00,2016-06-06 08:09:00,2016-06-06 08:21:00,NaT,2016-06-06 08:51:00,NaT,NaT,2016-06-06 09:18:00,2016-06-06 09:36:00,2016-06-06 09:48:00
10,0813,NaN,2016-06-06 08:00:00,2016-06-06 08:08:00,2016-06-06 08:21:00,2016-06-06 08:33:00,2016-06-06 08:45:00,2016-06-06 09:06:00,2016-06-06 09:19:00,2016-06-06 09:30:00,2016-06-06 09:45:00,2016-06-06 10:04:00,2016-06-06 10:18:00
11,0115,NaN,2016-06-06 08:24:00,2016-06-06 08:33:00,NaT,NaT,NaT,2016-06-06 09:15:00,NaT,NaT,NaT,NaT,2016-06-06 10:00:00
12,0615,NaN,2016-06-06 08:36:00,2016-06-06 08:45:00,2016-06-06 09:00:00,2016-06-06 09:13:00,NaT,2016-06-06 09:39:00,NaT,NaT,2016-06-06 10:04:00,2016-06-06 10:23:00,2016-06-06 10:36:00
13,1257,NaN,2016-06-06 08:54:00,2016-06-06 09:03:00,NaT,NaT,NaT,2016-06-06 09:46:00,NaT,NaT,2016-06-06 10:10:00,2016-06-06 10:29:00,2016-06-06 10:42:00
14,0819,NaN,2016-06-06 09:00:00,2016-06-06 09:08:00,2016-06-06 09:21:00,2016-06-06 09:33:00,2016-06-06 09:45:00,2016-06-06 10:06:00,2016-06-06 10:19:00,2016-06-06 10:30:00,2016-06-06 10:45:00,2016-06-06 11:04:00,2016-06-06 11:18:00
15,0121,NaN,2016-06-06 09:24:00,2016-06-06 09:33:00,NaT,NaT,NaT,2016-06-06 10:15:00,NaT,NaT,NaT,NaT,2016-06-06 11:00:00
16,0621,NaN,2016-06-06 09:36:00,2016-06-06 09:45:00,2016-06-06 10:00:00,2016-06-06 10:13:00,NaT,2016-06-06 10:39:00,NaT,NaT,2016-06-06 11:04:00,2016-06-06 11:23:00,2016-06-06 11:36:00
17,1259,NaN,2016-06-06 09:54:00,2016-06-06 10:03:00,NaT,NaT,NaT,2016-06-06 10:46:00,NaT,NaT,2016-06-06 11:10:00,2016-06-06 11:29:00,2016-06-06 11:42:00
18,0825,NaN,2016-06-06 10:00:00,2016-06-06 10:08:00,2016-06-06 10:21:00,2016-06-06 10:33:00,2016-06-06 10:45:00,2016-06-06 11:06:00,2016-06-06 11:19:00,2016-06-06 11:30:00,2016-06-06 11:45:00,2016-06-06 12:04:00,2016-06-06 12:18:00
19,0127,NaN,2016-06-06 10:24:00,2016-06-06 10:33:00,NaT,NaT,NaT,2016-06-06 11:15:00,NaT,NaT,NaT,NaT,2016-06-06 12:00:00
20,0627,NaN,2016-06-06 10:36:00,2016-06-06 10:45:00,2016-06-06 11:00:00,2016-06-06 11:13:00,NaT,2016-06-06 11:39:00,NaT,NaT,2016-06-06 12:04:00,2016-06-06 12:23:00,2016-06-06 12:36:00
21,1261,NaN,2016-06-06 10:54:00,2016-06-06 11:03:00,NaT,NaT,NaT,2016-06-06 11:46:00,NaT,NaT,2016-06-06 12:10:00,2016-06-06 12:29:00,2016-06-06 12:42:00
22,0831,NaN,2016-06-06 11:00:00,2016-06-06 11:08:00,2016-06-06 11:21:00,2016-06-06 11:33:00,2016-06-06 11:45:00,2016-06-06 12:06:00,2016-06-06 12:19:00,2016-06-06 12:30:00,2016-06-06 12:45:00,2016-06-06 13:04:00,2016-06-06 13:18:00
23,0133,NaN,2016-06-06 11:24:00,2016-06-06 11:33:00,NaT,NaT,NaT,2016-06-06 12:15:00,NaT,NaT,NaT,NaT,2016-06-06 13:00:00
24,0633,NaN,2016-06-06 11:36:00,2016-06-06 11:45:00,2016-06-06 12:00:00,2016-06-06 12:13:00,NaT,2016-06-06 12:39:00,NaT,NaT,2016-06-06 13:04:00,2016-06-06 13:23:00,2016-06-06 13:36:00
25,0837,NaN,2016-06-06 12:00:00,2016-06-06 12:08:00,2016-06-06 12:21:00,2016-06-06 12:33:00,2016-06-06 12:45:00,2016-06-06 13:06:00,2016-06-06 13:19:00,2016-06-06 13:30:00,2016-06-06 13:45:00,2016-06-06 14:04:00,2016-06-06 14:18:00
26,0139,NaN,2016-06-06 12:24:00,2016-06-06 12:33:00,NaT,NaT,NaT,2016-06-06 13:15:00,NaT,NaT,NaT,NaT,2016-06-06 14:00:00
27,0639,NaN,2016-06-06 12:36:00,2016-06-06 12:45:00,2016-06-06 13:00:00,2016-06-06 13:13:00,NaT,2016-06-06 13:39:00,NaT,NaT,2016-06-06 14:04:00,2016-06-06 14:23:00,2016-06-06 14:36:00
28,0843,NaN,2016-06-06 13:00:00,2016-06-06 13:08:00,2016-06-06 13:21:00,2016-06-06 13:33:00,2016-06-06 13:45:00,2016-06-06 14:06:00,2016-06-06 14:19:00,2016-06-06 14:30:00,2016-06-06 14:45:00,2016-06-06 15:04:00,2016-06-06 15:18:00
29,0145,NaN,2016-06-06 13:24:00,2016-06-06 13:33:00,NaT,NaT,NaT,2016-06-06 14:15:00,NaT,NaT,NaT,NaT,2016-06-06 15:00:00
30,0645,NaN,2016-06-06 13:36:00,2016-06-06 13:45:00,2016-06-06 14:00:00,2016-06-06 14:13:00,NaT,2016-06-06 14:39:00,NaT,NaT,2016-06-06 15:04:00,2016-06-06 15:23:00,2016-06-06 15:36:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35,0157,NaN,2016-06-06 15:24:00,2016-06-06 15:33:00,NaT,NaT,NaT,2016-06-06 16:15:00,NaT,NaT,NaT,NaT,2016-06-06 17:00:00
36,0657,NaN,2016-06-06 15:36:00,2016-06-06 15:45:00,2016-06-06 16:00:00,2016-06-06 16:13:00,NaT,2016-06-06 16:39:00,NaT,NaT,2016-06-06 17:04:00,2016-06-06 17:23:00,2016-06-06 17:36:00
37,0861,NaN,2016-06-06 16:00:00,2016-06-06 16:08:00,2016-06-06 16:21:00,2016-06-06 16:33:00,2016-06-06 16:45:00,2016-06-06 17:06:00,2016-06-06 17:19:00,2016-06-06 17:30:00,2016-06-06 17:45:00,2016-06-06 18:04:00,2016-06-06 18:18:00
38,0163,NaN,2016-06-06 16:24:00,2016-06-06 16:33:00,NaT,NaT,NaT,2016-06-06 17:15:00,NaT,NaT,NaT,NaT,2016-06-06 18:00:00
39,0663,NaN,2016-06-06 16:36:00,2016-06-06 16:45:00,2016-06-06 17:00:00,2016-06-06 17:13:00,NaT,2016-06-06 17:39:00,NaT,NaT,2016-06-06 18:04:00,2016-06-06 18:23:00,2016-06-06 18:36:00
40,1273,NaN,2016-06-06 16:54:00,2016-06-06 17:03:00,NaT,NaT,NaT,2016-06-06 17:46:00,NaT,NaT,2016-06-06 18:10:00,2016-06-06 18:29:00,2016-06-06 18:42:00
41,0867,NaN,2016-06-06 17:00:00,2016-06-06 17:08:00,2016-06-06 17:21:00,2016-06-06 17:33:00,2016-06-06 17:45:00,2016-06-06 18:06:00,2016-06-06 18:19:00,2016-06-06 18:30:00,2016-06-06 18:45:00,2016-06-06 19:04:00,2016-06-06 19:18:00
42,0169,NaN,2016-06-06 17:24:00,2016-06-06 17:33:00,NaT,NaT,NaT,2016-06-06 18:15:00,NaT,NaT,NaT,NaT,2016-06-06 19:00:00
43,0669,NaN,2016-06-06 17:36:00,2016-06-06 17:45:00,2016-06-06 18:00:00,2016-06-06 18:13:00,NaT,2016-06-06 18:39:00,NaT,NaT,2016-06-06 19:04:00,2016-06-06 19:23:00,2016-06-06 19:36:00
44,1275,NaN,2016-06-06 17:54:00,2016-06-06 18:03:00,NaT,NaT,NaT,2016-06-06 18:46:00,NaT,NaT,2016-06-06 19:10:00,2016-06-06 19:29:00,2016-06-06 19:42:00
45,0873,NaN,2016-06-06 18:00:00,2016-06-06 18:08:00,2016-06-06 18:21:00,2016-06-06 18:33:00,2016-06-06 18:45:00,2016-06-06 19:06:00,2016-06-06 19:19:00,2016-06-06 19:30:00,2016-06-06 19:45:00,2016-06-06 20:04:00,2016-06-06 20:18:00
46,1549,NaN,2016-06-06 18:18:00,2016-06-06 18:26:00,2016-06-06 18:39:00,2016-06-06 18:51:00,2016-06-06 19:03:00,2016-06-06 19:20:00,NaT,NaT,NaT,NaT,NaT
47,0175,NaN,2016-06-06 18:24:00,2016-06-06 18:33:00,NaT,NaT,NaT,2016-06-06 19:15:00,NaT,NaT,NaT,NaT,2016-06-06 20:00:00
48,0675,NaN,2016-06-06 18:36:00,2016-06-06 18:45:00,2016-06-06 19:00:00,2016-06-06 19:13:00,NaT,2016-06-06 19:39:00,NaT,NaT,2016-06-06 20:04:00,2016-06-06 20:23:00,2016-06-06 20:36:00
49,1177,NaN,2016-06-06 18:42:00,2016-06-06 18:50:00,NaT,NaT,NaT,2016-06-06 19:32:00,NaT,NaT,NaT,NaT,2016-06-06 20:24:00
50,0677,NaN,2016-06-06 18:48:00,2016-06-06 18:56:00,2016-06-06 19:09:00,2016-06-06 19:21:00,NaT,2016-06-06 19:51:00,NaT,NaT,2016-06-06 20:18:00,2016-06-06 20:36:00,2016-06-06 20:48:00
51,0879,NaN,2016-06-06 19:00:00,2016-06-06 19:08:00,2016-06-06 19:21:00,2016-06-06 19:33:00,2016-06-06 19:45:00,2016-06-06 20:06:00,2016-06-06 20:19:00,2016-06-06 20:30:00,2016-06-06 20:45:00,2016-06-06 21:04:00,2016-06-06 21:18:00
52,0181,NaN,2016-06-06 19:24:00,2016-06-06 19:33:00,NaT,NaT,NaT,2016-06-06 20:15:00,NaT,NaT,NaT,NaT,2016-06-06 21:00:00
53,0681,NaN,2016-06-06 19:36:00,2016-06-06 19:45:00,2016-06-06 20:00:00,2016-06-06 20:13:00,NaT,2016-06-06 20:39:00,NaT,NaT,2016-06-06 21:04:00,2016-06-06 21:23:00,2016-06-06 21:36:00
54,0885,NaN,2016-06-06 20:00:00,2016-06-06 20:08:00,2016-06-06 20:21:00,2016-06-06 20:33:00,2016-06-06 20:45:00,2016-06-06 21:06:00,2016-06-06 21:19:00,2016-06-06 21:30:00,2016-06-06 21:45:00,2016-06-06 22:04:00,2016-06-06 22:18:00
55,0187,NaN,2016-06-06 20:24:00,2016-06-06 20:33:00,NaT,NaT,NaT,2016-06-06 21:15:00,NaT,NaT,NaT,NaT,2016-06-06 22:00:00
56,0687,NaN,2016-06-06 20:36:00,2016-06-06 20:45:00,2016-06-06 21:00:00,2016-06-06 21:13:00,NaT,2016-06-06 21:39:00,NaT,NaT,2016-06-06 22:04:00,2016-06-06 22:23:00,2016-06-06 22:36:00
57,1281,NaN,2016-06-06 20:54:00,2016-06-06 21:03:00,NaT,NaT,NaT,2016-06-06 21:46:00,NaT,NaT,2016-06-06 22:10:00,2016-06-06 22:29:00,2016-06-06 22:42:00
58,0891,NaN,2016-06-06 21:00:00,2016-06-06 21:08:00,2016-06-06 21:21:00,2016-06-06 21:33:00,2016-06-06 21:45:00,2016-06-06 22:06:00,2016-06-06 22:19:00,2016-06-06 22:30:00,2016-06-06 22:45:00,2016-06-06 23:04:00,2016-06-06 23:18:00
59,0193,NaN,2016-06-06 21:24:00,2016-06-06 21:33:00,NaT,NaT,NaT,2016-06-06 22:15:00,NaT,NaT,NaT,NaT,2016-06-06 23:00:00
60,0693,NaN,2016-06-06 21:30:00,2016-06-06 21:38:00,2016-06-06 21:51:00,2016-06-06 22:02:00,NaT,2016-06-06 22:28:00,NaT,NaT,2016-06-06 22:53:00,2016-06-06 23:15:00,2016-06-06 23:30:00
61,0333,NaN,2016-06-06 21:54:00,NaT,2016-06-06 22:13:00,NaT,NaT,2016-06-06 22:45:00,2016-06-06 22:57:00,2016-06-06 23:07:00,2016-06-06 23:20:00,2016-06-06 23:39:00,2016-06-06 23:54:00
62,0295,NaN,2016-06-06 22:12:00,NaT,2016-06-06 22:31:00,NaT,NaT,2016-06-06 23:04:00,NaT,NaT,2016-06-06 23:28:00,2016-06-06 23:46:00,2016-06-06 23:59:00
63,0565,NaN,2016-06-06 22:18:00,2016-06-06 22:26:00,2016-06-06 22:39:00,2016-06-06 22:51:00,2016-06-06 23:03:00,2016-06-06 23:20:00,NaT,NaT,NaT,NaT,NaT
64,0577,NaN,2016-06-06 23:00:00,2016-06-06 23:08:00,2016-06-06 23:21:00,2016-06-06 23:32:00,2016-06-06 23:43:00,2016-06-06 23:59:00,NaT,NaT,NaT,NaT,NaT

In [6]:
disk_engine = create_engine('sqlite:///hsr_time_table.db') # Initializes database with filename 311_8M.db in current directory

In [7]:
south_bound.to_sql('table_201606', disk_engine, if_exists='append')

NameError: name 'south_bound' is not defined

In [8]:
date_object = dt.datetime.strptime('20160605 06:30', '%Y%m%d %H:%M')
epoch = dt.datetime.fromtimestamp(0)
(date_object - epoch).total_seconds()

1465079400.0

In [9]:
START_DATE = '20160606'[:-2]
START_DATE

'201606'